09-04-2025 14:41:05 - INFO - Logging system initialized. Environment: development
09-04-2025 14:41:05 - INFO - Hello
09-04-2025 14:41:05 - INFO - Model loaded from model_registry/model_storage/xgboost_20250403_102300_20250403_102301.pkl
09-04-2025 14:41:05 - INFO - Successfully loaded model from model_registry/model_storage/xgboost_20250403_102300_20250403_102301.pkl
09-04-2025 14:41:05 - INFO - Loaded credentials. Length: 3
09-04-2025 14:41:05 - INFO - Starting session with Capital.com...
09-04-2025 14:41:05 - INFO - About to start a new session.
09-04-2025 14:41:05 - INFO - Using encrypted password to start session.
09-04-2025 14:41:06 - INFO - AccountID and/or all_accounts is None. Initializing them now.
09-04-2025 14:41:06 - INFO - Will not print out response of all accounts.
09-04-2025 14:41:06 - INFO - Found accountId matching account USD_testing!
09-04-2025 14:41:06 - INFO - Successfully switched to account USD_testing!
09-04-2025 14:41:06 - INFO - Switched to demo account
09-04-2025 14:41:06 - INFO - LiveDataHandler processor thread started
09-04-2025 14:41:06 - INFO - Subscribing to GBPUSD MINUTE data...
09-04-2025 14:41:06 - INFO - Subscribing to live market data for GBPUSD at MINUTE resolution...
09-04-2025 14:41:06 - INFO - Websocket connected
09-04-2025 14:44:13 - INFO - Received keyboard interrupt, shutting down...
09-04-2025 14:44:13 - INFO - LiveDataHandler processor thread stopped
09-04-2025 14:44:13 - INFO - Data handler stopped
09-04-2025 14:44:13 - INFO - Ending session with Capital.com...
09-04-2025 14:44:13 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/Users/dmartinsen/pers-prog/ai-trading-v3/main.py", line 163, in <module>
    exit(main())
  File "/Users/dmartinsen/pers-prog/ai-trading-v3/main.py", line 160, in main
    run_live_integration.main(duration_minutes=60)
  File "/Users/dmartinsen/pers-prog/ai-trading-v3/live/run_live_integration.py", line 146, in main
    broker.end_session()
  File "/Users/dmartinsen/pers-prog/ai-trading-v3/broker/capital_com/capitalcom.py", line 48, in end_session
    return session.end_session(X_SECURITY_TOKEN=X_SECURITY_TOKEN or self.x_security_token, CST=CST or self.cst)
  File "/Users/dmartinsen/pers-prog/ai-trading-v3/broker/capital_com/rest_api/session.py", line 85, in end_session
    res = conn.getresponse()
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
